### ISSUE TITLE
Error on version 1.0.0

### ISSUE THREAD

**Issue by Dindaleon** [ColCh/isparta-instrumenter-loader#6]
I am getting this error after updating from v0.2.3 to v1.0.0

``` javascript
ERROR in ./utils.js
Module build failed: Error: Line 1: Unexpected token
    at constructError (C:\NodeServer\hapi-react-starter-kit\hapi-react-starter-kit\node_modules\esprima\esprima.js:2405:21)
    at createError (C:\NodeServer\hapi-react-starter-kit\hapi-react-starter-kit\node_modules\esprima\esprima.js:2424:17)
    at unexpectedTokenError (C:\NodeServer\hapi-react-starter-kit\hapi-react-starter-kit\node_modules\esprima\esprima.js:2498:13)
    at tolerateUnexpectedToken (C:\NodeServer\hapi-react-starter-kit\hapi-react-starter-kit\node_modules\esprima\esprima.js:2507:21)
    at parseStatementListItem (C:\NodeServer\hapi-react-starter-kit\hapi-react-starter-kit\node_modules\esprima\esprima.js:3971:21)
    at parseScriptBody (C:\NodeServer\hapi-react-starter-kit\hapi-react-starter-kit\node_modules\esprima\esprima.js:5491:25)
    at parseProgram (C:\NodeServer\hapi-react-starter-kit\hapi-react-starter-kit\node_modules\esprima\esprima.js:5507:16)
    at Object.parse (C:\NodeServer\hapi-react-starter-kit\hapi-react-starter-kit\node_modules\esprima\esprima.js:5691:23)
    at Instrumenter.instrumentSync (C:\NodeServer\hapi-react-starter-kit\hapi-react-starter-kit\node_modules\isparta\lib\instrumenter.js:68:39)
    at Object.module.exports (C:\NodeServer\hapi-react-starter-kit\hapi-react-starter-kit\node_modules\isparta-instrumenter-loader\index.js:20:25)
 @ ./test/components/Index.spec.js 11:13-35

ERROR in ./src/components/Index.js
Module build failed: SyntaxError: C:/NodeServer/hapi-react-starter-kit/hapi-react-starter-kit/src/components/Index.js: Unexpected token (21:3)
  19 |   render() {
  20 |     return (
> 21 |                  <div>
     |    ^
  22 |         <div><FormattedMessage {...messages.welcomeMessage} /></div>
  23 |                          <Link to={ '/home' } ><button><FormattedMessage { ...messages.takeMeHome } /></button></Link>
  24 |                  </div>
    at Parser.pp.raise (C:\NodeServer\hapi-react-starter-kit\hapi-react-starter-kit\node_modules\babel-core\node_modules\babylon\lib\parser\location.js:22:13)
    at Parser.pp.unexpected (C:\NodeServer\hapi-react-starter-kit\hapi-react-starter-kit\node_modules\babel-core\node_modules\babylon\lib\parser\util.js:91:8)
    at Parser.pp.parseExprAtom (C:\NodeServer\hapi-react-starter-kit\hapi-react-starter-kit\node_modules\babel-core\node_modules\babylon\lib\parser\expression.js:510:12)
    at Parser.pp.parseExprSubscripts (C:\NodeServer\hapi-react-starter-kit\hapi-react-starter-kit\node_modules\babel-core\node_modules\babylon\lib\parser\expression.js:265:19)
    at Parser.pp.parseMaybeUnary (C:\NodeServer\hapi-react-starter-kit\hapi-react-starter-kit\node_modules\babel-core\node_modules\babylon\lib\parser\expression.js:245:19)
    at Parser.pp.parseExprOps (C:\NodeServer\hapi-react-starter-kit\hapi-react-starter-kit\node_modules\babel-core\node_modules\babylon\lib\parser\expression.js:176:19)
    at Parser.pp.parseMaybeConditional (C:\NodeServer\hapi-react-starter-kit\hapi-react-starter-kit\node_modules\babel-core\node_modules\babylon\lib\parser\expression.js:158:19)
    at Parser.pp.parseMaybeAssign (C:\NodeServer\hapi-react-starter-kit\hapi-react-starter-kit\node_modules\babel-core\node_modules\babylon\lib\parser\expression.js:121:19)
    at Parser.pp.parseParenAndDistinguishExpression (C:\NodeServer\hapi-react-starter-kit\hapi-react-starter-kit\node_modules\babel-core\node_modules\babylon\lib\parser\expression.js:583:26)
    at Parser.pp.parseExprAtom (C:\NodeServer\hapi-react-starter-kit\hapi-react-starter-kit\node_modules\babel-core\node_modules\babylon\lib\parser\expression.js:469:19)
    at Parser.pp.parseExprSubscripts (C:\NodeServer\hapi-react-starter-kit\hapi-react-starter-kit\node_modules\babel-core\node_modules\babylon\lib\parser\expression.js:265:19)
    at Parser.pp.parseMaybeUnary (C:\NodeServer\hapi-react-starter-kit\hapi-react-starter-kit\node_modules\babel-core\node_modules\babylon\lib\parser\expression.js:245:19)
    at Parser.pp.parseExprOps (C:\NodeServer\hapi-react-starter-kit\hapi-react-starter-kit\node_modules\babel-core\node_modules\babylon\lib\parser\expression.js:176:19)
    at Parser.pp.parseMaybeConditional (C:\NodeServer\hapi-react-starter-kit\hapi-react-starter-kit\node_modules\babel-core\node_modules\babylon\lib\parser\expression.js:158:19)
    at Parser.pp.parseMaybeAssign (C:\NodeServer\hapi-react-starter-kit\hapi-react-starter-kit\node_modules\babel-core\node_modules\babylon\lib\parser\expression.js:121:19)
    at Parser.pp.parseExpression (C:\NodeServer\hapi-react-starter-kit\hapi-react-starter-kit\node_modules\babel-core\node_modules\babylon\lib\parser\expression.js:85:19)
 @ ./test/components/Index.spec.js 7:13-50
```

It does work fine on v0.2.3 so I believe should be a problem for the latest version.

**Comment by ColCh** [comment]
`v1.*` depends on `isparta@4`, which depends on `babel@6`. Are using `babel@6`? This might be a root

**Comment by Dindaleon** [comment]
Yes, I am using babel 6 and isparta 4. You can take a look: https://github.com/Dindaleon/hapi-react-starter-kit

**Comment by hitmands** [comment]
Same issue, cannot set up it as preloader:

``` javascript
Module build failed: Error: Line 1: Unexpected token
    at constructError (C:\projects\dodo-proposal\node_modules\esprima\esprima.js
:2405:21)
```

**Comment by lghiur** [comment]
does any one have any updates on this? I get the same thing :)

**Comment by ColCh** [comment]
I think that it's wrong babel setup. Who has example code to debug this? Please anybody.
I'm asking, because it "Works on my machine"

**Comment by hitmands** [comment]
I switched in favour of isparta-loader

**Comment by ColCh** [comment]
I have updated example dir as well: [example dir link](https://github.com/ColCh/isparta-instrumenter-loader/tree/d0eef6912b9a593997b4c7dd041d9d50635c460c/example)

Please take a look at it.

Docs link: [Passing options to isparta](https://github.com/ColCh/isparta-instrumenter-loader#passing-options-to-isparta)
